version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: faceit-cli-kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      # KRaft mode configuration
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      
      # Topic configuration
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
      # JMX configuration
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      
      # Log configuration
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: faceit-cli-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      # No Zookeeper needed for KRaft mode

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: faceit-cli-kafka-init
    depends_on:
      - kafka
    command: |
      bash -c "
        echo 'Waiting for Kafka KRaft to be ready...'
        sleep 10
        kafka-topics --bootstrap-server kafka:29092 --list
        echo 'Creating faceit-cli-logs topic...'
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic faceit-cli-logs --partitions 3 --replication-factor 1
        echo 'Topic created successfully!'
        kafka-topics --bootstrap-server kafka:29092 --list
      "
    restart: "no"

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    container_name: faceit-cli-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - zipkin
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=faceit-cli-collector,service.version=1.0.0

  # Zipkin for trace visualization
  zipkin:
    image: openzipkin/zipkin:3.3
    container_name: faceit-cli-zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=zipkin-mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Jaeger as alternative trace backend (optional)
  # jaeger:
  #   image: jaegertracing/all-in-one:1.55
  #   container_name: faceit-cli-jaeger
  #   ports:
  #     - "16686:16686"  # Jaeger UI
  #     - "14250:14250"  # Jaeger gRPC
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   profiles:
  #     - jaeger

volumes:
  kafka-data: