name: Build and Push Docker Images

# This workflow runs only when application or Docker files are changed
# Triggers: internal/**, main.go, go.mod, go.sum, Dockerfile, .dockerignore, docker workflow
on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
    paths:
      - 'internal/**'                    # Core application code
      - 'main.go'                        # Main application entry point
      - 'go.mod'                         # Go module dependencies
      - 'go.sum'                         # Go module checksums
      - 'Dockerfile'                     # Docker configuration
      - '.dockerignore'                  # Docker ignore file
      - '.github/workflows/docker.yml'   # This workflow file
#   pull_request:
    # branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
