name: Release

# Release workflow runs only on tag creation (e.g., v1.0.0)
# No path filtering needed as it's triggered by tags, not file changes
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
      
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/bazel
        key: bazel-cache-${{ runner.os }}-${{ hashFiles('**/BUILD.bazel', '**/WORKSPACE', '**/MODULE.bazel') }}
        restore-keys: |
          bazel-cache-${{ runner.os }}-
        
    - name: Run tests
      run: bazel test //... --test_tag_filters=-integration
      
    - name: Build for multiple platforms
      run: |
        # Create release directory
        mkdir -p release
        
        # Build for different platforms using Bazel
        bazel build //:faceit-cli --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64
        cp bazel-bin/faceit-cli_/faceit-cli release/faceit-cli-linux-amd64
        
        bazel build //:faceit-cli --platforms=@io_bazel_rules_go//go/toolchain:linux_arm64
        cp bazel-bin/faceit-cli_/faceit-cli release/faceit-cli-linux-arm64
        
        bazel build //:faceit-cli --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64
        cp bazel-bin/faceit-cli_/faceit-cli release/faceit-cli-windows-amd64.exe
        
        bazel build //:faceit-cli --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64
        cp bazel-bin/faceit-cli_/faceit-cli release/faceit-cli-darwin-amd64
        
        bazel build //:faceit-cli --platforms=@io_bazel_rules_go//go/toolchain:darwin_arm64
        cp bazel-bin/faceit-cli_/faceit-cli release/faceit-cli-darwin-arm64
        
    - name: Create checksums
      run: |
        cd release
        sha256sum * > checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Downloads
          
          Download the appropriate binary for your platform:
          
          - **Linux (amd64)**: `faceit-cli-linux-amd64`
          - **Linux (arm64)**: `faceit-cli-linux-arm64`
          - **Windows (amd64)**: `faceit-cli-windows-amd64.exe`
          - **macOS (amd64)**: `faceit-cli-darwin-amd64`
          - **macOS (arm64)**: `faceit-cli-darwin-arm64`
          
          ## Verification
          
          Verify your download with the checksums in `checksums.txt`.
        files: |
          release/*
